# Configuration principale du plugin CustomMobs

# Paramètres généraux
general:
  # Langue du plugin (fr, en)
  language: "fr"
  # Activer les messages de debug
  debug: false

# Contrôle des mobs
mob-control:
  # Désactiver le spawn naturel des monstres
  disable-natural-spawns: true
  # Supprimer les mobs inutiles (chauves-souris, calmars, etc.)
  remove-useless-mobs: true
  # Empêcher les mobs de détruire les blocs
  prevent-mob-grief: true

# Paramètres des monstres custom
custom-mobs:
  # Autoriser les monstres custom à détruire des blocs
  allow-block-damage: false
  # Multiplicateur de dégâts global
  damage-multiplier: 1.0
  # Multiplicateur de vie global
  health-multiplier: 1.0
  # Distance maximale de détection des joueurs
  detection-range: 20.0

# Zones de spawn
spawn-zones:
  faille:
    world: "Cave"
    min-x: -3
    min-y: -24
    min-z: -38
    max-x: 27
    max-y: -18
    max-z: -16
    mob-types:
      - "skeleton_archer"
      - "spider_venomous"
      - "witch_cursed"
      - "geode_aberration"
    max-mobs: 25
    group-size: 4
    spawn-interval: 30  # en secondes
    enabled: true

  entree_pvp:
    world: "Cave"
    min-x: -1
    min-y: -20
    min-z: 37
    max-x: 21
    max-y: -17
    max-z: 72
    mob-types:
      - "spider_venomous"
      - "skeleton_archer"
      - "creeper_explosive"
    max-mobs: 20
    group-size: 3
    spawn-interval: 45
    enabled: true

  # Exemple de zone - Montagnes rocheuses
  grotte1:
    world: "Cave"
    min-x: 37
    min-y: -17
    min-z: 87
    max-x: 15
    max-y: -11
    max-z: 97
    mob-types:
      - "zombie_warrior"
      - "golem_stone"
      - "necromancer_dark"
    max-mobs: 8
    group-size: 3
    spawn-interval: 45
    enabled: true

  grotte2:
    world: "Cave"
    min-x: -46
    min-y: -19
    min-z: 147
    max-x: -29
    max-y: -12
    max-z: 128
    mob-types:
      - "skeleton_archer"
      - "dragon_fire"
    max-mobs: 8
    group-size: 3
    spawn-interval: 45
    enabled: true

  grotte3:
    world: "Cave"
    min-x: -54
    min-y: -14
    min-z: 109
    max-x: -61
    max-y: -12
    max-z: 114
    mob-types:
      - "creeper_explosive"
      - "skeleton_archer"
      - "golem_stone"
    max-mobs: 12
    group-size: 3
    spawn-interval: 45
    enabled: true

  grotte4:
    world: "Cave"
    min-x: -39
    min-y: -3
    min-z: 117
    max-x: -53
    max-y: -2
    max-z: 130
    mob-types:
      - "skeleton_archer"
      - "spider_venomous"
      - "witch_cursed"
    max-mobs: 12
    group-size: 3
    spawn-interval: 45
    enabled: true

  outside:
    world: "Cave"
    min-x: -9
    min-y: -20
    min-z: 139
    max-x: 22
    max-y: -18
    max-z: 106
    mob-types:
      - "skeleton_archer"
      - "zombie_warrior"
      - "creeper_explosive"
    max-mobs: 12
    group-size: 3
    spawn-interval: 45
    enabled: true

  outsidegrotte:
    world: "Cave"
    min-x: 14
    min-y: -8
    min-z: 121
    max-x: 19
    max-y: -4
    max-z: 135
    mob-types:
      - "golem_stone"
      - "creeper_explosive"
    max-mobs: 6
    group-size: 2
    spawn-interval: 45
    enabled: true

  outsideentree:
    world: "Cave"
    min-x: -42
    min-y: -21
    min-z: 107
    max-x: 2
    max-y: -17
    max-z: 76
    mob-types:
      - "skeleton_archer"
      - "zombie_warrior"
      - "creeper_explosive"
    max-mobs: 30
    group-size: 3
    spawn-interval: 45
    enabled: true

# Système de loots
loot-system:
  # Multiplicateur de chance global
  chance-multiplier: 1.0
  # Autoriser les loots vanilla en plus des custom
  allow-vanilla-drops: false
  # XP supplémentaire pour les monstres custom
  bonus-exp-multiplier: 1.5

# Optimisation
optimization:
  # Nombre max de projectiles dans un monde
  max-projectiles: 100
  # Nombre max d'items au sol dans un monde
  max-items: 200